### ISSUE TITLE
Icon Size too big

### ISSUE THREAD

**Issue by moonclimber1** [davunt/app-eraser#4]
**Describe the bug**
Icon Size on macOS is too big

**To Reproduce**
Install Application
Open it

**Expected behavior**
Icon size should be correct according to the apple style guidelines
some information: https://bootcamp.uxdesign.cc/creating-app-icons-for-macos-11-and-up-1132ccd479bc

**Screenshots** 
<img width="205" alt="Bildschirmfoto 2022-12-12 um 00 49 25" src="https://user-images.githubusercontent.com/55745851/206936439-b80b8db9-0825-4520-b61d-a67f3710a560.png">

**Comment by davunt** [comment]
Thanks for link. Should be a pretty quick fix 👍🏻

**Comment by davunt** [comment]
This has now been resolved in the latest versions.
